name: Selenium Tests

on: 
  push:
    branches:
      - master    # or master, depending on your default branch
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Build and run Docker container
      run: |
        docker compose up -d
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Chrome Driver
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dpkg -i google-chrome-stable_current_amd64.deb || apt-get -fy install
        
    - name: Run script
      run: |
        python tests/Adsterra.py
